version: '2'

services:
  imap:
    # Uncomment this for build image in local
    build:
      context: .
    #image: antespi/docker-imap-devel:latest
    container_name: imap
    ports:
    - "25:25"
    - "143:143"
    - "993:993"
    environment:
    - MAILNAME=example.com
    - MAIL_ADDRESS=bob@example.com
    - MAIL_PASS=password
    restart: always
    volumes:
    - imap_mail:/var/mail
    - imap_certs:/etc/ssl
volumes:
  imap_certs:
    driver: local
  imap_mail:
    driver: local
